import React from 'react';
import '../../styles/create_flash_cards_page/generate_content_chat_pop_up_box.scss'
// @ts-ignore
const GenerateContentChatPopUpBox = ({ boxOpen, boxContent, acceptContent, rejectContent, id }) => {
    return (
        <div className={`dialog ${boxOpen ? 'open' : ''}`}>
            <div className="dialog-overlay"></div>
            <div className="dialog-box">
                <div className="dialog-header">
                    <h2>Please note that the information generated by the chatGPT may not always be accurate, and users should not blindly trust the information provided</h2>
                </div>
                <div className="dialog-content">
                    <p>{boxContent}</p>
                </div>
                <div className="dialog-actions">
                    <button onClick={() => acceptContent(id)} className="accept-btn">Accept</button>
                    <button onClick={rejectContent} className="reject-btn">Reject</button>
                </div>
            </div>
        </div>
    );
};

export default GenerateContentChatPopUpBox;