import React from 'react';
import '../../styles/create_flash_cards_page/generate_content_chat_pop_up_box.scss'
// @ts-ignore
const GenerateContentChatPopUpBox = ({ boxOpen, boxContent, acceptContent, rejectContent, id }) => {
    return (
        <div className={`dialog-chat ${boxOpen ? 'open' : ''}`}>
            <div className="dialog-overlay-chat"></div>
            <div className="dialog-box-chat">
                <div className="dialog-header-chat">
                    <h2>Please note that the information generated by the chatGPT may not always be accurate, and users should not blindly trust the information provided</h2>
                </div>
                <div className="dialog-content-chat">
                    <p>{boxContent}</p>
                </div>
                <div className="dialog-actions-chat">
                    <button onClick={() => acceptContent(id)} className="accept-btn-chat">Accept</button>
                    <button onClick={rejectContent} className="reject-btn-chat">Reject</button>
                </div>
            </div>
        </div>
    );
};

export default GenerateContentChatPopUpBox;