version: "3.9"

services:
  fc_db:
    image: "mariadb:11.0"
    container_name: fc_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Fla5hcard5r00t
      MYSQL_DATABASE: flash_cards
      MYSQL_USER: flashcards
      MYSQL_PASSWORD: Fla5hcard5
    networks:
      - fc_db_net

  fc_api:
    container_name: 'fc_api'
    image: fc_api
    ports:
      - 8000:8000
    build:
      context: .
    restart: always
    env_file:
      - .env.dev
    volumes:
      - .:/fc_api
      - media:/media
    networks:
      - fc_api_net
      - fc_db_net
    command: sh docker-entrypoint.sh
    depends_on:
      - fc_db

networks:
  fc_db_net:
    driver: bridge
    name: fc_db_net

  fc_api_net:
    driver: bridge
    name: fc_api_net

volumes:
  media:
